version: '3.8'
name: sequential-search
services:
 mssql:
    image: sequential-search-mssql
    container_name: mssql
    restart: always
    build:
      context: ..
      dockerfile: Api/Dockerfile.mssql
      no_cache: true
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password01"
    ports:
      - "1433:1433"
    expose:
      - 1433
 mssql-migration:
    image: sequential-search-migration
    container_name: migration
    build:
      context: ..
      dockerfile: Api/Dockerfile.migration
      no_cache: true
    environment:
       - ConnectionString=${ConnectionString}
    depends_on:
        - mssql
        - webapi
 mssql-sql-functions:
    image: sequential-search-sql-functions
    container_name: sql-functions
    build:
      context: ..
      dockerfile: Api/Dockerfile.sqlfunctions
      no_cache: true
      #хранение данных временное, нужно вернуться и проверить забираются ли из .env
    environment:
       - ConnectionString=${ConnectionString}
       - SQL_SERVER=host.docker.internal,1433
       - SQL_DATABASE=SequentialSearch
       - SQL_USER=SA
       - SQL_PASSWORD=Password01
    depends_on:
        - mssql
 webapi:
    image: sequential-search-webapi
    container_name: webapi
    restart: always
    build:
      context: ..
      dockerfile: Api/Dockerfile
      no_cache: true
    ports:
      - "8080:54414"